### PR TITLE
Change server send timing to logging_start

### PR DESCRIPTION
**Pull request by Jefftree**
Issue Link: https://github.com/Yelp/py_zipkin/issues/42

Fixes server send timing to more accurately reflect when server send actually occurs.

Removed the `logging_start` annotation (since it'll be the same as Server Send) and added a `logging_end` annotation

### CODE REVIEW

**Comment by bplotnick** [comment]
Yes, I believe the root span duration should be changed as well (I'm curious as to how the zipkin UI will render this).

Also, you will need to remove `logging_end` and probably add `logging_end` in place of where `ss` used to be.

**Comment by Jefftree** [comment]
@bplotnick We current don't have a field for `logging_end`, do you mean adding an extra annotation `logging_end`?

**Comment by bplotnick** [comment]
Whoops. I meant remove `logging_start` and add `logging_end`. And yeah I mean add it as an annotation (basically what we did for `logging_start`)

**Comment by bplotnick** [comment]
Can you also update the docstring for `zipkin.py:zipkin_span.__init__`?

Other than that, it looks good to me.

**Comment by bplotnick** [comment]
:shipit:

**Comment by kaisen** [comment]
👌 🚢

**Pull request merged**
