### PR TITLE
Rebuild protobuf using protoc 3.19

### PR DESCRIPTION
**Pull request by xiao-chen**
Previous attempt at https://github.com/Yelp/py_zipkin/pull/163 failed tests since unit tests doesn't check `installed` (which makes sense...).

https://github.com/Yelp/py_zipkin/pull/164/files tries to pin protobuf version to prevent running into this problem, but that limits the protobuf version.

It seems like rebuilding the protobuf file with protoc 3.20 can make this work, as suggested by the error message.
```
18:20:54 E   If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
```

### CODE REVIEW

**Comment by yaroliakh** [comment]
Test are still failing for older python versions. Please recompile using protobuf 3.19 since starting 3.20 they dropped support for python <3.7: https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0-rc1

**Comment by xiao-chen** [comment]
Yeah I can recompile with https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.0.
I don't know what to do with python2.7 - the protobuf error message says `protoc >= 3.19.0.`. If py_zipkin wants to support 2.7, maybe there should be a separate branch/tag/whatever for that...

**Comment by xiao-chen** [comment]
Rebuilt with 3.19.0

**Comment by xiao-chen** [comment]
hi @acer618 I see your review on https://github.com/Yelp/py_zipkin/pull/164 - any thoughts on this PR?
With protobuf recompiled, there is no need to lock it to be <4 (except for python 2.7...)

**Comment by xiao-chen** [comment]
Hi @acer618 @drolando , could you please take a look?

**Comment by acer618** [comment]
> Hi @acer618 @drolando , could you please take a look?

Hi @xiao-chen , instead we are working on dropping support for python 2.7

**Comment by acer618** [comment]
> Thanks for the update @acer618 . Just to make sure I understand, the plan is that once 2.7 is dropped, we'll be able to go ahead with this PR and solve the protobuf issue (for now)?

yes we are currently working on dropping 2.7 support. we should have this done by end of today (june 9th)

**Comment by xiao-chen** [comment]
Hi @acer618 , I see that you cut a 1.0.0 tag already with py 2.7 dropped and this commit incorporated. Thanks for the work!

It doesn't look like the 1.0.0 release is on pypi yet https://pypi.org/project/py-zipkin/#history. Could you help check why? (It seems like https://github.com/Yelp/py_zipkin/blob/master/.travis.yml#L37 maybe part of why, if that helps...)

**Comment by xiao-chen** [comment]
Closing this since the commit is merged already as part of the work dropping 2.7 support.

**Pull request closed without merging**
