### PR TITLE
start and stop span manual

### PR DESCRIPTION
**Pull request by GuoJing**
Context manager is good but not easy for some framework. This should be easy for some Python framework like flask:

```python
#some middleware
@bp.before_request
def before():
    span.start()

@bp.after_request
def before():
    span.stop()
```

### CODE REVIEW

**Comment by mjbryant** [comment]
You can do this right now like:

```python
span = zipkin_span('service')
span.__enter__()
span.__exit__(None, None, None)
```

But this _is_ cleaner. I'm okay with adding this nicer syntax. @bplotnick, @kaisen: thoughts?

**Comment by bplotnick** [comment]
👍 

This seems much cleaner than calling the enter/exit functions

**Comment by kaisen** [comment]
no objections here. looks like nice syntactic sugar.

**Comment by mjbryant** [comment]
This is available on PyPI as v0.4.0.

**Comment by GuoJing** [comment]
Thanks guys!

**Pull request merged**
