### PR TITLE
Add 'py_zipkin.logging_start' default annotation

### PR DESCRIPTION
**Pull request by mjbryant**
@kaisen, @bplotnick what do you think?

### CODE REVIEW

**Comment by bplotnick** [comment]
What's the use case here? I think this sort of measurement is more useful for us as developers of the framework, but I don't see the use to an application developer.

Maybe this would be useful as an option if someone wants to see how much overhead the instrumentation is adding, but I don't know if this is appropriate as a default.

**Comment by mjbryant** [comment]
The use case is to see how much total time is spent in the user's transport_handler. In our case, this is to help us figure out how much we'd gain by switching to a faster transport_handler (such as offloading the actual log generation to a mule). This really feels like something that should be measured. I was looking at some traces earlier and they had these big unaccounted for sections, and I found out that it was due to this. Any other suggestions on ways to do this?

**Comment by kaisen** [comment]
Hmm...do you think the trace would be too noisy if we wrapped client span logging with it's own zipkin_span? Then we could see time spent in transport_handler as a span.

**Comment by mjbryant** [comment]
@kaisen i considered that... i think that's too noisy.

**Comment by mjbryant** [comment]
After some offline discussion, we're going to refactor this to exit the logging context *after* filtering annotations, while adding the 'server' filter to the root span automatically. This will allow us to get rid of adding annotations during logging context manager exit.

For bonus points we can also change the `ZipkinLoggingContext` to not be a contextmanager, since we're not using it as such anyway.

**Comment by bplotnick** [comment]
🚢

**Comment by kaisen** [comment]
:shipit:

**Comment by bplotnick** [comment]
Just for posterity, after _more_ discussion, it was decided to just make the logging annotation optional (which is reflected in the last commit)

**Pull request merged**
